import Nav from "@/components/user/layout/Nav";
import "../globals.css";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <main>{children}</main>;
}
