import { SidebarAdmin } from "@/components/admin/SidebarAdmin";
import "../globals.css";

export const metadata = {
  title: "admin of E-com",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html>
      <body>
        <SidebarAdmin>
          <div>{children}</div>
        </SidebarAdmin>
      </body>
    </html>
  );
}

export default RootLayout;
