import { SidebarAdmin } from "@/components/admin/SidebarAdmin";
import "../globals.css";
import { getAuthStatus } from "@/lib/auth";
import  Link  from "next/link";


export const metadata = {
  title: "admin of E-com",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getAuthStatus(); // ✅ Await the async call
  console.log("👤 User status:", user);

  if (!user || !user.isAdmin || user.status !== "Active") {
    return (
      
        <main className="flex justify-center items-center h-screen text-xl text-red-600 gap-20">
          Access Denied – Admins only
          <Link
            href="/login"
            className="bg-amber-300 px-5 py-2 w-20 h-12 flex justify-center items-center rounded"
          >
            Login
          </Link>
       </main>
      
    );
  }

  return (
    <main>
        <SidebarAdmin>
          {children}
        </SidebarAdmin>
      
    </main>
  );
}