import Nav from "@/components/user/nav";
import "../globals.css";
import { getAuthStatus } from "@/lib/auth";
import CategoryNavigation from "@/components/user/categoryNavigation";
import Footer from "@/components/user/footer";


export const metadata = {
  title: "E-com-demo",
  description: "Generated by create next app",


};

export default async function RootLayout({ children }) {

    const user = await getAuthStatus(); // ✅ Await the async call
    console.log("👤 User status:", user);
  

  return (
    <main>
      <Nav user={user} />
      <header className=" pt-16">
        <CategoryNavigation />
      </header>
      {children}
      <footer>
        <Footer/>
      </footer>
    </main>
  );
}
