name: Build and deploy Node.js app to Azure Web App - Tajbee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Recommended for Next.js 15

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: .next
          retention-days: 1

      - name: Upload public folder (if any)
        if: ${{ fs.existsSync('public') }}
        uses: actions/upload-artifact@v4
        with:
          name: public-folder
          path: public
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download built app
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: .next

      - name: Download public folder
        uses: actions/download-artifact@v4
        with:
          name: public-folder
          path: public
        if: ${{ steps.download_public.outputs.download-skip-reason != 'not_found' }}

      - name: Download root files (package.json, etc.)
        uses: actions/checkout@v4

      # Copy required root files
      - name: Copy root files
        run: |
          cp package.json .npmrc .env* . || true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_331BC5638EBE461ABACAC0231F480322 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75BA99A0B1A54F7F910FF65128117776 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75E26E5ED3F443D99DB33D91F87B10E1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Tajbee'
          slot-name: 'Production'
          package: .
